-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaPpQcwAlpSJrAvlw
ZDf+3xgu8l3g7UaUXm0hCV3/jNygCgYIKoZIzj0DAQehRANCAASvilmRe0S+ojy5
ENc5wi+JqSJ02nGdjXaETKBGJ16XUioBF2dTQlXkpB3uApeXwKqLc8h4Suu/HtYp
E0nqU2Jw
-----END PRIVATE KEY-----